package com.example.demo.models.generateentities;
// Generated Apr 27, 2023, 11:39:00 AM by Hibernate Tools 6.1.5.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String passwod;
	private int age;

	public User() {
	}

	public User(String name, String passwod, int age) {
		this.name = name;
		this.passwod = passwod;
		this.age = age;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPasswod() {
		return this.passwod;
	}

	public void setPasswod(String passwod) {
		this.passwod = passwod;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

}
